name: Sync branches

on:
  pull_request:
    types:
      - closed
      
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and configure hub
        run: |
          sudo snap install hub --classic
          echo "github.com:\n- oauth_token: \${{ secrets.GITHUB_TOKEN }}" >> ~/.config/hub

      - name: Open PR to main-emea
        run: |
          # pr_author_name=${{ env.name }}
          
          git checkout -b sync-main-emea
          git merge --no-ff origin/main-emea -m "Sync from PR #${original_pr_number} - ${{ github.event.pull_request.title }}"
          #git pull --rebase origin main-emea
          git push origin sync-main-emea
          hub pull-request -b main-emea -h sync-main-emea -m "Sync from main->main-emea from PR #${{ github.event.pull_request.number }}" -a ${{ github.event.pull_request.sender }} 

      - name: Open PR to main-apac
        run: |
          original_pr_number=${{ steps.get_original_pr_number.outputs.original_pr_number }}
          git config user.name "${{ steps.get_pr_author.outputs.name }}"
          git config user.email "${{ steps.get_pr_author.outputs.email }}"
          git checkout -b sync-main-apac
          git push origin sync-main-apac
          hub pull-request -b main-apac -h sync-main-apac -m "Sync from main->main-apac from PR #${{ github.event.pull_request.number }}"

      - name: Open PR to main-na
        run: |
          original_pr_number=${{ steps.get_original_pr_number.outputs.original_pr_number }}
          git config user.name "${{ steps.get_pr_author.outputs.name }}"
          git config user.email "${{ steps.get_pr_author.outputs.email }}"
          git checkout -b sync-main-na
          git push origin sync-main-na
          hub pull-request -b main-na -h sync-main-na -m "Sync from main->main-na from PR #${original_pr_number}"
