name: Sync main branches

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main-emea
      run: git checkout -B main-emea && git merge -m "[skip ci]" --no-ff ${{ github.ref }}

    - name: Push changes to main-emea
      run: git push -f origin main:main-emea

    - name: Merge to main-apac
      run: git checkout -B main-apac && git merge --no-ff ${{ github.ref }}

    - name: Push changes to main-apac
      run: git push origin main-apac

    - name: Merge to main-na
      run: git checkout -B main-na && git merge --no-ff ${{ github.ref }}

    - name: Push changes to main-na
      run: git push origin main-na
